<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>EVE-O Preview</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="EveOPreview.app.manifest" />
    <None Remove="costura.costura.dll.compressed" />
    <None Remove="costura.lightinject.dll.compressed" />
    <None Remove="costura.mediatr.dll.compressed" />
    <None Remove="costura.newtonsoft.json.dll.compressed" />
    <None Remove="costura.system.valuetuple.dll.compressed" />
    <EmbeddedResource Include="EveOPreview.app.manifest" LogicalName="EveOPreview.app.manifest" />
    <EmbeddedResource Include="costura.costura.dll.compressed" LogicalName="costura.costura.dll.compressed" />
    <EmbeddedResource Include="costura.lightinject.dll.compressed" LogicalName="costura.lightinject.dll.compressed" />
    <EmbeddedResource Include="costura.mediatr.dll.compressed" LogicalName="costura.mediatr.dll.compressed" />
    <EmbeddedResource Include="costura.newtonsoft.json.dll.compressed" LogicalName="costura.newtonsoft.json.dll.compressed" />
    <EmbeddedResource Include="costura.system.valuetuple.dll.compressed" LogicalName="costura.system.valuetuple.dll.compressed" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core" />
    <Reference Include="LightInject">
      <HintPath>work/LightInject.dll</HintPath>
    </Reference>
    <Reference Include="MediatR">
      <HintPath>work/MediatR.dll</HintPath>
    </Reference>
    <Reference Include="WindowsBase" />
    <Reference Include="Newtonsoft.Json">
      <HintPath>work/Newtonsoft.Json.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>